version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  ajax-app:
    depends_on:
      - mongo
      - nats
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.data.mongodb.database":"ajax",
              "spring.data.mongodb.port":"27017",
              "nats.connection.url":"nats://nats:4222"
      }'
    container_name: "docker-app"
    ports:
      - "8080:8080"

volumes:
  mongo:
