spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://mongo:27017/ajax
      #uri: mongodb://localhost:27017/ajax


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ora.romaniuk@gmail.com
    password: fjxi gawn pgjl huxy
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            required: true


  main:
    allow-bean-definition-overriding: true
