name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      nats:
        image: nats:latest
        ports:
          - "4222:4222"

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
