name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Start mongodb
        run: docker run -d --name mongo -p 27017:27017 mongo:latest

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build
